2025-03-13 10:40:24,659 - distributed.nanny - INFO -         Start Nanny at: 'tcp://172.26.1.37:39817'
2025-03-13 10:40:44,136 - distributed.worker - INFO -       Start worker at:    tcp://172.26.1.37:37475
2025-03-13 10:40:44,136 - distributed.worker - INFO -          Listening to:    tcp://172.26.1.37:37475
2025-03-13 10:40:44,137 - distributed.worker - INFO -           Worker name:             SLURMCluster-1
2025-03-13 10:40:44,137 - distributed.worker - INFO -          dashboard at:          172.26.1.37:34741
2025-03-13 10:40:44,137 - distributed.worker - INFO - Waiting to connect to:    tcp://172.26.1.35:35869
2025-03-13 10:40:44,137 - distributed.worker - INFO - -------------------------------------------------
2025-03-13 10:40:44,137 - distributed.worker - INFO -               Threads:                          1
2025-03-13 10:40:44,137 - distributed.worker - INFO -                Memory:                   9.31 GiB
2025-03-13 10:40:44,137 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space-84860/worker-8gr7l1lr
2025-03-13 10:40:44,137 - distributed.worker - INFO - -------------------------------------------------
2025-03-13 10:40:54,241 - distributed.worker - INFO - Starting Worker plugin shuffle
2025-03-13 10:40:54,242 - distributed.worker - INFO -         Registered to:    tcp://172.26.1.35:35869
2025-03-13 10:40:54,242 - distributed.worker - INFO - -------------------------------------------------
2025-03-13 10:40:54,243 - distributed.core - INFO - Starting established connection to tcp://172.26.1.35:35869
2025-03-13 10:52:14,871 - distributed.core - INFO - Connection to tcp://172.26.1.35:35869 has been closed.
2025-03-13 10:52:14,892 - distributed.worker - INFO - Stopping worker at tcp://172.26.1.37:37475. Reason: worker-handle-scheduler-connection-broken
2025-03-13 10:52:14,893 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/tornado/iostream.py", line 861, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/tornado/iostream.py", line 1116, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/worker.py", line 1252, in heartbeat
    response = await retry_operation(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/utils_comm.py", line 452, in retry_operation
    return await retry(
           ^^^^^^^^^^^^
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/utils_comm.py", line 431, in retry
    return await coro()
           ^^^^^^^^^^^^
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/core.py", line 1395, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/core.py", line 1154, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/home/lstaub/miniforge3/envs/wrfhydro_huc12_agg/lib/python3.11/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://172.26.1.37:49716 remote=tcp://172.26.1.35:35869>: ConnectionResetError: [Errno 104] Connection reset by peer
2025-03-13 10:52:15,024 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://172.26.1.37:39817'. Reason: worker-handle-scheduler-connection-broken
2025-03-13 10:52:15,026 - distributed.nanny - INFO - Worker closed
2025-03-13 10:52:18,015 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.26.1.37:39817'. Reason: nanny-close-gracefully
2025-03-13 10:52:18,016 - distributed.dask_worker - INFO - End worker
